sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms/simple'
            contexts:   [admin]

sonata_admin:
    templates:
        # default global templates
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        user_block: DbuConferenceBundle:Admin:topnav.html.twig
    extensions:
        cmf_core.admin_extension.translatable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
            excludes:
                - dbu_conference.admin.speaker
                - dbu_conference.admin.room
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
            excludes:
                - dbu_conference.admin.room
    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }

sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page:
             valid_children:
                 - all
        Dbu\ConferenceBundle\Document\Room:
             valid_children:
                 - Dbu\ConferenceBundle\Document\Presentation
        Dbu\ConferenceBundle\Document\Presentation:
             valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Dbu\ConferenceBundle\Document\RecentlyAddedBlock
        Dbu\ConferenceBundle\Document\Speaker: ~
        Dbu\ConferenceBundle\Document\RecentlyAddedBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock: ~
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
                - Dbu\ConferenceBundle\Document\RecentlyAddedBlock
