home_redirect:
    pattern: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: /cms/simple
        statusCode: 301
        useReferrer: false

login:
    path:   /{_locale}/login
    defaults:  { _controller: DbuConferenceBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout

dbu_conference_subscribe:
    path: /{_locale}/subscribe
    defaults: { _controller: DbuConferenceBundle:Subscribe:subscribe }

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"
create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

_imagine:
    resource: .
    type:     imagine

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin
sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

# redirect routes for the non-locale routes
admin_without_locale:
    pattern: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_without_locale:
    pattern: /admin/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
cmf_tree:
    resource: .
    type: 'cmf_tree'
